language: node_js
node_js:
  - node
script: echo hello; echo $GITHUB_TOKEN

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: asd
    on:
      branch: main
      tags: false
  - provider: npm
    skip_cleanup: true
    email: "giacomo.venturini3@gmail.com"
    api_token: $NPM_TOKEN
    token: $NPM_TOKEN
    on:
      branch: main
      tags: true
